language: java
jdk: oraclejdk8
deploy:
  provider: heroku
  app: destination-api-remembranza
  api_key:
    secure: AI7YFyYifiJvWlgQWfDNviWFChwjvTyzjD78y9wj8AvpkU9exD0WDbF6zHkN55CG/sxTGmvsxiNvxYZSc9C5ToqXst0x13nTZswYsQscvgSuTb+riQMGKtDf4WyvjwnjF9X2kF90eJ+EJHDOpZy099Hgb30j7PEg/Do8fxUEvNsHhEIoPnmaryzxIxBkHEtDuvT/Oio6LG3NTwwjhdM77IR/yAFNgya0cMXeG6pa9zMuy6RXvv3iIEzSVmR04e0VTrOlMJQG/95fAbe1jzz5aJ+Jrm7lqg4/Czp+uu48GWofE1JB8s+ozMABCmUo5jitl6Mga+8hjpbPXvYTNrRRMs3WKzgfBC5xhtH5RYbsNhBeouKrH6FlmZPYZH/PxcCEv1NXB6bLYXh4CHX+XOQrE2Z/HgFf+2kj95U3npFUvobcK5HGYNANeIFA4LB6PwnYV9sP8ZtmL9dFWExPS4NFtStfF7kL1TOi8qWSbwKYegk21rlMOuAWUDLIbVDxnZ76wbhxhWpPkQHWyy/Xe/lHxwj3WZch7h1M9biObw4ULOhjsL6ksnlTva+rBMOpzXLm+Z/e60WRmf3FD9pabpP8iG2qoIYSI09m4rF5s/gG2Fpnig3/j7d4VLnkMPMEsCBqIuvKe/FgntN7byhB+2SuUYSkDEjIMx6fZcqzvRLVQcM=
